### ISSUE TITLE
MiniTest:Spec works, but output is strange

### ISSUE THREAD

**Issue by pablox-cl** [qrush/m#76]
`m` works fine, but the run options doesn't look pretty:

```shell
> m test/validator_test.rb:18
Run options: -n "/^(test_0001_should\\ have\\ two\\ parameters,\\ file\\ and\\ type|test_0002_second\\ parameter\\ it's\\ optional\\ and\\ should\\ be\\ inferred\\ from\\ the\\ file\\ name)$/" --seed 4599

# Running:

..

Finished in 0.000649s, 3080.0695 runs/s, 3080.0695 assertions/s.

2 runs, 2 assertions, 0 failures, 0 errors, 0 skips
```

I'm using spec, with the it "should blabalbla", so I guess there's some regexp / replace wrong? If you can direct me to the necessary test I can fix it myself and send a PR.

Regards!

**Comment by zamith** [comment]
What would you expect to see?

In order to run the minitest tests, we need to use the name of the methods, I guess that `MiniTest::Spec` DSL adds `test_XXXX` as a prefix to the methods, so they can ensure uniqueness.

I believe this is not an issue that can be fixed by `m`, so I'm closing it, but feel free to open it again if that's not the case.

**Comment by pablox-cl** [comment]
I was referring to the second line, my test file it's not called that way:

```shell
Run options: -n "/^(test_0001_should\\ have\\ two\\ parameters,\\ file\\ and\\ type|test_0002_second\\ parameter\\ it's\\ optional\\ and\\ should\\ be\\ inferred\\ from\\ the\\ file\\ name)$/" --seed 4599```

So that's why I was wondering on why is showing that.
